// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD0RLcUA8z2_Xm8tw1x4UtUhSnKmtH8n4',
    appId: '1:1040620901:web:84db3e22bd6490884ed58c',
    messagingSenderId: '1040620901',
    projectId: 'agapecarecb-e1be4',
    authDomain: 'agapecarecb-e1be4.firebaseapp.com',
    storageBucket: 'agapecarecb-e1be4.firebasestorage.app',
    measurementId: 'G-Y2ESD7XS82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFVPUIo_F3ipPp4nGuTzxqLtZD4mU4E0o',
    appId: '1:1040620901:android:7e3ffcbd8f82052c4ed58c',
    messagingSenderId: '1040620901',
    projectId: 'agapecarecb-e1be4',
    storageBucket: 'agapecarecb-e1be4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF8ywnfRX5YRRd4H7bIqPC8LPrQj1u-kE',
    appId: '1:1040620901:ios:bf0e49c9baa4d2104ed58c',
    messagingSenderId: '1040620901',
    projectId: 'agapecarecb-e1be4',
    storageBucket: 'agapecarecb-e1be4.firebasestorage.app',
    iosBundleId: 'com.example.agapecares',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF8ywnfRX5YRRd4H7bIqPC8LPrQj1u-kE',
    appId: '1:1040620901:ios:bf0e49c9baa4d2104ed58c',
    messagingSenderId: '1040620901',
    projectId: 'agapecarecb-e1be4',
    storageBucket: 'agapecarecb-e1be4.firebasestorage.app',
    iosBundleId: 'com.example.agapecares',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD0RLcUA8z2_Xm8tw1x4UtUhSnKmtH8n4',
    appId: '1:1040620901:web:5ff59b5b087735574ed58c',
    messagingSenderId: '1040620901',
    projectId: 'agapecarecb-e1be4',
    authDomain: 'agapecarecb-e1be4.firebaseapp.com',
    storageBucket: 'agapecarecb-e1be4.firebasestorage.app',
    measurementId: 'G-H9E426RBRC',
  );
}
